//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_DetalleRequerimiento_Material", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.Material), "DetalleRequerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.DetalleRequerimiento), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_DetalleRequerimiento_Requerimiento", "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.Requerimiento), "DetalleRequerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.DetalleRequerimiento), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_DetalleSolicitud_Material", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.Material), "DetalleSolicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.DetalleSolicitud), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_DetalleSolicitud_Solicitud", "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.Solicitud), "DetalleSolicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.DetalleSolicitud), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_Solicitud_Estacion", "Estacion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.Estacion), "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.Solicitud), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_Inventario_Material", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.Material), "Inventario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.Inventario), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_Inventario_Requerimiento", "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.Requerimiento), "Inventario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.Inventario), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_Inventario_Solicitud", "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.Solicitud), "Inventario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.Inventario), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_Requerimiento_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.Usuario), "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.Requerimiento), true)]
[assembly: EdmRelationshipAttribute("CSCInventariosDBModel", "FK_Solicitud_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.Usuario), "Solicitud", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.Solicitud), true)]

#endregion

namespace Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CSCInventariosDBEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CSCInventariosDBEntities usando la cadena de conexión encontrada en la sección 'CSCInventariosDBEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public CSCInventariosDBEntities() : base("name=CSCInventariosDBEntities", "CSCInventariosDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CSCInventariosDBEntities.
        /// </summary>
        public CSCInventariosDBEntities(string connectionString) : base(connectionString, "CSCInventariosDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CSCInventariosDBEntities.
        /// </summary>
        public CSCInventariosDBEntities(EntityConnection connection) : base(connection, "CSCInventariosDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleRequerimiento> DetalleRequerimiento
        {
            get
            {
                if ((_DetalleRequerimiento == null))
                {
                    _DetalleRequerimiento = base.CreateObjectSet<DetalleRequerimiento>("DetalleRequerimiento");
                }
                return _DetalleRequerimiento;
            }
        }
        private ObjectSet<DetalleRequerimiento> _DetalleRequerimiento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleSolicitud> DetalleSolicitud
        {
            get
            {
                if ((_DetalleSolicitud == null))
                {
                    _DetalleSolicitud = base.CreateObjectSet<DetalleSolicitud>("DetalleSolicitud");
                }
                return _DetalleSolicitud;
            }
        }
        private ObjectSet<DetalleSolicitud> _DetalleSolicitud;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Estacion> Estacion
        {
            get
            {
                if ((_Estacion == null))
                {
                    _Estacion = base.CreateObjectSet<Estacion>("Estacion");
                }
                return _Estacion;
            }
        }
        private ObjectSet<Estacion> _Estacion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Inventario> Inventario
        {
            get
            {
                if ((_Inventario == null))
                {
                    _Inventario = base.CreateObjectSet<Inventario>("Inventario");
                }
                return _Inventario;
            }
        }
        private ObjectSet<Inventario> _Inventario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Material> Material
        {
            get
            {
                if ((_Material == null))
                {
                    _Material = base.CreateObjectSet<Material>("Material");
                }
                return _Material;
            }
        }
        private ObjectSet<Material> _Material;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Requerimiento> Requerimiento
        {
            get
            {
                if ((_Requerimiento == null))
                {
                    _Requerimiento = base.CreateObjectSet<Requerimiento>("Requerimiento");
                }
                return _Requerimiento;
            }
        }
        private ObjectSet<Requerimiento> _Requerimiento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Solicitud> Solicitud
        {
            get
            {
                if ((_Solicitud == null))
                {
                    _Solicitud = base.CreateObjectSet<Solicitud>("Solicitud");
                }
                return _Solicitud;
            }
        }
        private ObjectSet<Solicitud> _Solicitud;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleRequerimiento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleRequerimiento(DetalleRequerimiento detalleRequerimiento)
        {
            base.AddObject("DetalleRequerimiento", detalleRequerimiento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleSolicitud. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleSolicitud(DetalleSolicitud detalleSolicitud)
        {
            base.AddObject("DetalleSolicitud", detalleSolicitud);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Estacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEstacion(Estacion estacion)
        {
            base.AddObject("Estacion", estacion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Inventario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToInventario(Inventario inventario)
        {
            base.AddObject("Inventario", inventario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Material. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMaterial(Material material)
        {
            base.AddObject("Material", material);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Requerimiento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRequerimiento(Requerimiento requerimiento)
        {
            base.AddObject("Requerimiento", requerimiento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Solicitud. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSolicitud(Solicitud solicitud)
        {
            base.AddObject("Solicitud", solicitud);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="DetalleRequerimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleRequerimiento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleRequerimiento.
        /// </summary>
        /// <param name="dr_id">Valor inicial de la propiedad dr_id.</param>
        /// <param name="rq_id">Valor inicial de la propiedad rq_id.</param>
        /// <param name="material_id">Valor inicial de la propiedad material_id.</param>
        public static DetalleRequerimiento CreateDetalleRequerimiento(global::System.Int32 dr_id, global::System.Int32 rq_id, global::System.Int32 material_id)
        {
            DetalleRequerimiento detalleRequerimiento = new DetalleRequerimiento();
            detalleRequerimiento.dr_id = dr_id;
            detalleRequerimiento.rq_id = rq_id;
            detalleRequerimiento.material_id = material_id;
            return detalleRequerimiento;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dr_id
        {
            get
            {
                return _dr_id;
            }
            set
            {
                if (_dr_id != value)
                {
                    Ondr_idChanging(value);
                    ReportPropertyChanging("dr_id");
                    _dr_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dr_id");
                    Ondr_idChanged();
                }
            }
        }
        private global::System.Int32 _dr_id;
        partial void Ondr_idChanging(global::System.Int32 value);
        partial void Ondr_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rq_id
        {
            get
            {
                return _rq_id;
            }
            set
            {
                Onrq_idChanging(value);
                ReportPropertyChanging("rq_id");
                _rq_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rq_id");
                Onrq_idChanged();
            }
        }
        private global::System.Int32 _rq_id;
        partial void Onrq_idChanging(global::System.Int32 value);
        partial void Onrq_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 material_id
        {
            get
            {
                return _material_id;
            }
            set
            {
                Onmaterial_idChanging(value);
                ReportPropertyChanging("material_id");
                _material_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("material_id");
                Onmaterial_idChanged();
            }
        }
        private global::System.Int32 _material_id;
        partial void Onmaterial_idChanging(global::System.Int32 value);
        partial void Onmaterial_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dr_cantidad_rq
        {
            get
            {
                return _dr_cantidad_rq;
            }
            set
            {
                Ondr_cantidad_rqChanging(value);
                ReportPropertyChanging("dr_cantidad_rq");
                _dr_cantidad_rq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dr_cantidad_rq");
                Ondr_cantidad_rqChanged();
            }
        }
        private Nullable<global::System.Int32> _dr_cantidad_rq;
        partial void Ondr_cantidad_rqChanging(Nullable<global::System.Int32> value);
        partial void Ondr_cantidad_rqChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dr_cantidad_ingreso
        {
            get
            {
                return _dr_cantidad_ingreso;
            }
            set
            {
                Ondr_cantidad_ingresoChanging(value);
                ReportPropertyChanging("dr_cantidad_ingreso");
                _dr_cantidad_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dr_cantidad_ingreso");
                Ondr_cantidad_ingresoChanged();
            }
        }
        private Nullable<global::System.Int32> _dr_cantidad_ingreso;
        partial void Ondr_cantidad_ingresoChanging(Nullable<global::System.Int32> value);
        partial void Ondr_cantidad_ingresoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleRequerimiento_Material", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleRequerimiento_Material", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleRequerimiento_Material", "Material").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleRequerimiento_Material", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleRequerimiento_Material", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleRequerimiento_Requerimiento", "Requerimiento")]
        public Requerimiento Requerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Requerimiento", "Requerimiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Requerimiento", "Requerimiento").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Requerimiento> RequerimientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Requerimiento", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Requerimiento", "Requerimiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="DetalleSolicitud")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleSolicitud : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleSolicitud.
        /// </summary>
        /// <param name="ds_id">Valor inicial de la propiedad ds_id.</param>
        /// <param name="sl_id">Valor inicial de la propiedad sl_id.</param>
        public static DetalleSolicitud CreateDetalleSolicitud(global::System.Int32 ds_id, global::System.Int32 sl_id)
        {
            DetalleSolicitud detalleSolicitud = new DetalleSolicitud();
            detalleSolicitud.ds_id = ds_id;
            detalleSolicitud.sl_id = sl_id;
            return detalleSolicitud;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ds_id
        {
            get
            {
                return _ds_id;
            }
            set
            {
                if (_ds_id != value)
                {
                    Onds_idChanging(value);
                    ReportPropertyChanging("ds_id");
                    _ds_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ds_id");
                    Onds_idChanged();
                }
            }
        }
        private global::System.Int32 _ds_id;
        partial void Onds_idChanging(global::System.Int32 value);
        partial void Onds_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sl_id
        {
            get
            {
                return _sl_id;
            }
            set
            {
                Onsl_idChanging(value);
                ReportPropertyChanging("sl_id");
                _sl_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_id");
                Onsl_idChanged();
            }
        }
        private global::System.Int32 _sl_id;
        partial void Onsl_idChanging(global::System.Int32 value);
        partial void Onsl_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> material_id
        {
            get
            {
                return _material_id;
            }
            set
            {
                Onmaterial_idChanging(value);
                ReportPropertyChanging("material_id");
                _material_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("material_id");
                Onmaterial_idChanged();
            }
        }
        private Nullable<global::System.Int32> _material_id;
        partial void Onmaterial_idChanging(Nullable<global::System.Int32> value);
        partial void Onmaterial_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ds_cantidad_solicitada
        {
            get
            {
                return _ds_cantidad_solicitada;
            }
            set
            {
                Onds_cantidad_solicitadaChanging(value);
                ReportPropertyChanging("ds_cantidad_solicitada");
                _ds_cantidad_solicitada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ds_cantidad_solicitada");
                Onds_cantidad_solicitadaChanged();
            }
        }
        private Nullable<global::System.Int32> _ds_cantidad_solicitada;
        partial void Onds_cantidad_solicitadaChanging(Nullable<global::System.Int32> value);
        partial void Onds_cantidad_solicitadaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ds_cantidad_asignada
        {
            get
            {
                return _ds_cantidad_asignada;
            }
            set
            {
                Onds_cantidad_asignadaChanging(value);
                ReportPropertyChanging("ds_cantidad_asignada");
                _ds_cantidad_asignada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ds_cantidad_asignada");
                Onds_cantidad_asignadaChanged();
            }
        }
        private Nullable<global::System.Int32> _ds_cantidad_asignada;
        partial void Onds_cantidad_asignadaChanging(Nullable<global::System.Int32> value);
        partial void Onds_cantidad_asignadaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ds_cantidad_aceptada
        {
            get
            {
                return _ds_cantidad_aceptada;
            }
            set
            {
                Onds_cantidad_aceptadaChanging(value);
                ReportPropertyChanging("ds_cantidad_aceptada");
                _ds_cantidad_aceptada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ds_cantidad_aceptada");
                Onds_cantidad_aceptadaChanged();
            }
        }
        private Nullable<global::System.Int32> _ds_cantidad_aceptada;
        partial void Onds_cantidad_aceptadaChanging(Nullable<global::System.Int32> value);
        partial void Onds_cantidad_aceptadaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleSolicitud_Material", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleSolicitud_Material", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleSolicitud_Material", "Material").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleSolicitud_Material", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("CSCInventariosDBModel.FK_DetalleSolicitud_Material", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleSolicitud_Solicitud", "Solicitud")]
        public Solicitud Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Solicitud", "Solicitud").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Solicitud", "Solicitud").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Solicitud> SolicitudReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Solicitud", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Solicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Solicitud", "Solicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="Estacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Estacion.
        /// </summary>
        /// <param name="estacion_id">Valor inicial de la propiedad estacion_id.</param>
        public static Estacion CreateEstacion(global::System.Int32 estacion_id)
        {
            Estacion estacion = new Estacion();
            estacion.estacion_id = estacion_id;
            return estacion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estacion_id
        {
            get
            {
                return _estacion_id;
            }
            set
            {
                if (_estacion_id != value)
                {
                    Onestacion_idChanging(value);
                    ReportPropertyChanging("estacion_id");
                    _estacion_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("estacion_id");
                    Onestacion_idChanged();
                }
            }
        }
        private global::System.Int32 _estacion_id;
        partial void Onestacion_idChanging(global::System.Int32 value);
        partial void Onestacion_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estacion_nombre
        {
            get
            {
                return _estacion_nombre;
            }
            set
            {
                Onestacion_nombreChanging(value);
                ReportPropertyChanging("estacion_nombre");
                _estacion_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estacion_nombre");
                Onestacion_nombreChanged();
            }
        }
        private global::System.String _estacion_nombre;
        partial void Onestacion_nombreChanging(global::System.String value);
        partial void Onestacion_nombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estacion_zona
        {
            get
            {
                return _estacion_zona;
            }
            set
            {
                Onestacion_zonaChanging(value);
                ReportPropertyChanging("estacion_zona");
                _estacion_zona = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estacion_zona");
                Onestacion_zonaChanged();
            }
        }
        private global::System.String _estacion_zona;
        partial void Onestacion_zonaChanging(global::System.String value);
        partial void Onestacion_zonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estacion_coordenadas
        {
            get
            {
                return _estacion_coordenadas;
            }
            set
            {
                Onestacion_coordenadasChanging(value);
                ReportPropertyChanging("estacion_coordenadas");
                _estacion_coordenadas = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estacion_coordenadas");
                Onestacion_coordenadasChanged();
            }
        }
        private global::System.String _estacion_coordenadas;
        partial void Onestacion_coordenadasChanging(global::System.String value);
        partial void Onestacion_coordenadasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estacion_referencia
        {
            get
            {
                return _estacion_referencia;
            }
            set
            {
                Onestacion_referenciaChanging(value);
                ReportPropertyChanging("estacion_referencia");
                _estacion_referencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estacion_referencia");
                Onestacion_referenciaChanged();
            }
        }
        private global::System.String _estacion_referencia;
        partial void Onestacion_referenciaChanging(global::System.String value);
        partial void Onestacion_referenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> estacion_eliminado
        {
            get
            {
                return _estacion_eliminado;
            }
            set
            {
                Onestacion_eliminadoChanging(value);
                ReportPropertyChanging("estacion_eliminado");
                _estacion_eliminado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estacion_eliminado");
                Onestacion_eliminadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _estacion_eliminado;
        partial void Onestacion_eliminadoChanging(Nullable<global::System.Boolean> value);
        partial void Onestacion_eliminadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Solicitud_Estacion", "Solicitud")]
        public EntityCollection<Solicitud> Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Solicitud>("CSCInventariosDBModel.FK_Solicitud_Estacion", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Solicitud>("CSCInventariosDBModel.FK_Solicitud_Estacion", "Solicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="Inventario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Inventario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Inventario.
        /// </summary>
        /// <param name="inventario_id">Valor inicial de la propiedad inventario_id.</param>
        /// <param name="material_id">Valor inicial de la propiedad material_id.</param>
        public static Inventario CreateInventario(global::System.Int32 inventario_id, global::System.Int32 material_id)
        {
            Inventario inventario = new Inventario();
            inventario.inventario_id = inventario_id;
            inventario.material_id = material_id;
            return inventario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 inventario_id
        {
            get
            {
                return _inventario_id;
            }
            set
            {
                if (_inventario_id != value)
                {
                    Oninventario_idChanging(value);
                    ReportPropertyChanging("inventario_id");
                    _inventario_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("inventario_id");
                    Oninventario_idChanged();
                }
            }
        }
        private global::System.Int32 _inventario_id;
        partial void Oninventario_idChanging(global::System.Int32 value);
        partial void Oninventario_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sl_id
        {
            get
            {
                return _sl_id;
            }
            set
            {
                Onsl_idChanging(value);
                ReportPropertyChanging("sl_id");
                _sl_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_id");
                Onsl_idChanged();
            }
        }
        private Nullable<global::System.Int32> _sl_id;
        partial void Onsl_idChanging(Nullable<global::System.Int32> value);
        partial void Onsl_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rq_id
        {
            get
            {
                return _rq_id;
            }
            set
            {
                Onrq_idChanging(value);
                ReportPropertyChanging("rq_id");
                _rq_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rq_id");
                Onrq_idChanged();
            }
        }
        private Nullable<global::System.Int32> _rq_id;
        partial void Onrq_idChanging(Nullable<global::System.Int32> value);
        partial void Onrq_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> inventario_cantidad_rq_entrada
        {
            get
            {
                return _inventario_cantidad_rq_entrada;
            }
            set
            {
                Oninventario_cantidad_rq_entradaChanging(value);
                ReportPropertyChanging("inventario_cantidad_rq_entrada");
                _inventario_cantidad_rq_entrada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inventario_cantidad_rq_entrada");
                Oninventario_cantidad_rq_entradaChanged();
            }
        }
        private Nullable<global::System.Int32> _inventario_cantidad_rq_entrada;
        partial void Oninventario_cantidad_rq_entradaChanging(Nullable<global::System.Int32> value);
        partial void Oninventario_cantidad_rq_entradaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> inventario_cantidad_sl_salida
        {
            get
            {
                return _inventario_cantidad_sl_salida;
            }
            set
            {
                Oninventario_cantidad_sl_salidaChanging(value);
                ReportPropertyChanging("inventario_cantidad_sl_salida");
                _inventario_cantidad_sl_salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inventario_cantidad_sl_salida");
                Oninventario_cantidad_sl_salidaChanged();
            }
        }
        private Nullable<global::System.Int32> _inventario_cantidad_sl_salida;
        partial void Oninventario_cantidad_sl_salidaChanging(Nullable<global::System.Int32> value);
        partial void Oninventario_cantidad_sl_salidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_movimiento
        {
            get
            {
                return _fecha_movimiento;
            }
            set
            {
                Onfecha_movimientoChanging(value);
                ReportPropertyChanging("fecha_movimiento");
                _fecha_movimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_movimiento");
                Onfecha_movimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_movimiento;
        partial void Onfecha_movimientoChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_movimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 material_id
        {
            get
            {
                return _material_id;
            }
            set
            {
                Onmaterial_idChanging(value);
                ReportPropertyChanging("material_id");
                _material_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("material_id");
                Onmaterial_idChanged();
            }
        }
        private global::System.Int32 _material_id;
        partial void Onmaterial_idChanging(global::System.Int32 value);
        partial void Onmaterial_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Inventario_eliminado
        {
            get
            {
                return _Inventario_eliminado;
            }
            set
            {
                OnInventario_eliminadoChanging(value);
                ReportPropertyChanging("Inventario_eliminado");
                _Inventario_eliminado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inventario_eliminado");
                OnInventario_eliminadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Inventario_eliminado;
        partial void OnInventario_eliminadoChanging(Nullable<global::System.Boolean> value);
        partial void OnInventario_eliminadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Inventario_Material", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_Inventario_Material", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_Inventario_Material", "Material").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("CSCInventariosDBModel.FK_Inventario_Material", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("CSCInventariosDBModel.FK_Inventario_Material", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Inventario_Requerimiento", "Requerimiento")]
        public Requerimiento Requerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_Inventario_Requerimiento", "Requerimiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_Inventario_Requerimiento", "Requerimiento").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Requerimiento> RequerimientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_Inventario_Requerimiento", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Requerimiento>("CSCInventariosDBModel.FK_Inventario_Requerimiento", "Requerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Inventario_Solicitud", "Solicitud")]
        public Solicitud Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("CSCInventariosDBModel.FK_Inventario_Solicitud", "Solicitud").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("CSCInventariosDBModel.FK_Inventario_Solicitud", "Solicitud").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Solicitud> SolicitudReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Solicitud>("CSCInventariosDBModel.FK_Inventario_Solicitud", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Solicitud>("CSCInventariosDBModel.FK_Inventario_Solicitud", "Solicitud", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="Material")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Material : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Material.
        /// </summary>
        /// <param name="material_id">Valor inicial de la propiedad material_id.</param>
        public static Material CreateMaterial(global::System.Int32 material_id)
        {
            Material material = new Material();
            material.material_id = material_id;
            return material;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 material_id
        {
            get
            {
                return _material_id;
            }
            set
            {
                if (_material_id != value)
                {
                    Onmaterial_idChanging(value);
                    ReportPropertyChanging("material_id");
                    _material_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("material_id");
                    Onmaterial_idChanged();
                }
            }
        }
        private global::System.Int32 _material_id;
        partial void Onmaterial_idChanging(global::System.Int32 value);
        partial void Onmaterial_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String material_nombre
        {
            get
            {
                return _material_nombre;
            }
            set
            {
                Onmaterial_nombreChanging(value);
                ReportPropertyChanging("material_nombre");
                _material_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("material_nombre");
                Onmaterial_nombreChanged();
            }
        }
        private global::System.String _material_nombre;
        partial void Onmaterial_nombreChanging(global::System.String value);
        partial void Onmaterial_nombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String material_modelo
        {
            get
            {
                return _material_modelo;
            }
            set
            {
                Onmaterial_modeloChanging(value);
                ReportPropertyChanging("material_modelo");
                _material_modelo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("material_modelo");
                Onmaterial_modeloChanged();
            }
        }
        private global::System.String _material_modelo;
        partial void Onmaterial_modeloChanging(global::System.String value);
        partial void Onmaterial_modeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> material_cantidad
        {
            get
            {
                return _material_cantidad;
            }
            set
            {
                Onmaterial_cantidadChanging(value);
                ReportPropertyChanging("material_cantidad");
                _material_cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("material_cantidad");
                Onmaterial_cantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _material_cantidad;
        partial void Onmaterial_cantidadChanging(Nullable<global::System.Int32> value);
        partial void Onmaterial_cantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String material_observacion
        {
            get
            {
                return _material_observacion;
            }
            set
            {
                Onmaterial_observacionChanging(value);
                ReportPropertyChanging("material_observacion");
                _material_observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("material_observacion");
                Onmaterial_observacionChanged();
            }
        }
        private global::System.String _material_observacion;
        partial void Onmaterial_observacionChanging(global::System.String value);
        partial void Onmaterial_observacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> material_eliminado
        {
            get
            {
                return _material_eliminado;
            }
            set
            {
                Onmaterial_eliminadoChanging(value);
                ReportPropertyChanging("material_eliminado");
                _material_eliminado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("material_eliminado");
                Onmaterial_eliminadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _material_eliminado;
        partial void Onmaterial_eliminadoChanging(Nullable<global::System.Boolean> value);
        partial void Onmaterial_eliminadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String material_marca
        {
            get
            {
                return _material_marca;
            }
            set
            {
                Onmaterial_marcaChanging(value);
                ReportPropertyChanging("material_marca");
                _material_marca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("material_marca");
                Onmaterial_marcaChanged();
            }
        }
        private global::System.String _material_marca;
        partial void Onmaterial_marcaChanging(global::System.String value);
        partial void Onmaterial_marcaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleRequerimiento_Material", "DetalleRequerimiento")]
        public EntityCollection<DetalleRequerimiento> DetalleRequerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleRequerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Material", "DetalleRequerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleRequerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Material", "DetalleRequerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleSolicitud_Material", "DetalleSolicitud")]
        public EntityCollection<DetalleSolicitud> DetalleSolicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleSolicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Material", "DetalleSolicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleSolicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Material", "DetalleSolicitud", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Inventario_Material", "Inventario")]
        public EntityCollection<Inventario> Inventario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inventario>("CSCInventariosDBModel.FK_Inventario_Material", "Inventario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inventario>("CSCInventariosDBModel.FK_Inventario_Material", "Inventario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="Requerimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Requerimiento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Requerimiento.
        /// </summary>
        /// <param name="rq_id">Valor inicial de la propiedad rq_id.</param>
        public static Requerimiento CreateRequerimiento(global::System.Int32 rq_id)
        {
            Requerimiento requerimiento = new Requerimiento();
            requerimiento.rq_id = rq_id;
            return requerimiento;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rq_id
        {
            get
            {
                return _rq_id;
            }
            set
            {
                if (_rq_id != value)
                {
                    Onrq_idChanging(value);
                    ReportPropertyChanging("rq_id");
                    _rq_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rq_id");
                    Onrq_idChanged();
                }
            }
        }
        private global::System.Int32 _rq_id;
        partial void Onrq_idChanging(global::System.Int32 value);
        partial void Onrq_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usuario_id
        {
            get
            {
                return _usuario_id;
            }
            set
            {
                Onusuario_idChanging(value);
                ReportPropertyChanging("usuario_id");
                _usuario_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usuario_id");
                Onusuario_idChanged();
            }
        }
        private Nullable<global::System.Int32> _usuario_id;
        partial void Onusuario_idChanging(Nullable<global::System.Int32> value);
        partial void Onusuario_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> rq_fecha
        {
            get
            {
                return _rq_fecha;
            }
            set
            {
                Onrq_fechaChanging(value);
                ReportPropertyChanging("rq_fecha");
                _rq_fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rq_fecha");
                Onrq_fechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _rq_fecha;
        partial void Onrq_fechaChanging(Nullable<global::System.DateTime> value);
        partial void Onrq_fechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> rq_validacion
        {
            get
            {
                return _rq_validacion;
            }
            set
            {
                Onrq_validacionChanging(value);
                ReportPropertyChanging("rq_validacion");
                _rq_validacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rq_validacion");
                Onrq_validacionChanged();
            }
        }
        private Nullable<global::System.Boolean> _rq_validacion;
        partial void Onrq_validacionChanging(Nullable<global::System.Boolean> value);
        partial void Onrq_validacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> rq_eliminado
        {
            get
            {
                return _rq_eliminado;
            }
            set
            {
                Onrq_eliminadoChanging(value);
                ReportPropertyChanging("rq_eliminado");
                _rq_eliminado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rq_eliminado");
                Onrq_eliminadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _rq_eliminado;
        partial void Onrq_eliminadoChanging(Nullable<global::System.Boolean> value);
        partial void Onrq_eliminadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleRequerimiento_Requerimiento", "DetalleRequerimiento")]
        public EntityCollection<DetalleRequerimiento> DetalleRequerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleRequerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Requerimiento", "DetalleRequerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleRequerimiento>("CSCInventariosDBModel.FK_DetalleRequerimiento_Requerimiento", "DetalleRequerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Inventario_Requerimiento", "Inventario")]
        public EntityCollection<Inventario> Inventario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inventario>("CSCInventariosDBModel.FK_Inventario_Requerimiento", "Inventario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inventario>("CSCInventariosDBModel.FK_Inventario_Requerimiento", "Inventario", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Requerimiento_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CSCInventariosDBModel.FK_Requerimiento_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CSCInventariosDBModel.FK_Requerimiento_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CSCInventariosDBModel.FK_Requerimiento_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("CSCInventariosDBModel.FK_Requerimiento_Usuario", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="Solicitud")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Solicitud : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Solicitud.
        /// </summary>
        /// <param name="sl_id">Valor inicial de la propiedad sl_id.</param>
        public static Solicitud CreateSolicitud(global::System.Int32 sl_id)
        {
            Solicitud solicitud = new Solicitud();
            solicitud.sl_id = sl_id;
            return solicitud;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sl_id
        {
            get
            {
                return _sl_id;
            }
            set
            {
                if (_sl_id != value)
                {
                    Onsl_idChanging(value);
                    ReportPropertyChanging("sl_id");
                    _sl_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sl_id");
                    Onsl_idChanged();
                }
            }
        }
        private global::System.Int32 _sl_id;
        partial void Onsl_idChanging(global::System.Int32 value);
        partial void Onsl_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usuario_id
        {
            get
            {
                return _usuario_id;
            }
            set
            {
                Onusuario_idChanging(value);
                ReportPropertyChanging("usuario_id");
                _usuario_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usuario_id");
                Onusuario_idChanged();
            }
        }
        private Nullable<global::System.Int32> _usuario_id;
        partial void Onusuario_idChanging(Nullable<global::System.Int32> value);
        partial void Onusuario_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> estacion_id
        {
            get
            {
                return _estacion_id;
            }
            set
            {
                Onestacion_idChanging(value);
                ReportPropertyChanging("estacion_id");
                _estacion_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estacion_id");
                Onestacion_idChanged();
            }
        }
        private Nullable<global::System.Int32> _estacion_id;
        partial void Onestacion_idChanging(Nullable<global::System.Int32> value);
        partial void Onestacion_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sl_fecha
        {
            get
            {
                return _sl_fecha;
            }
            set
            {
                Onsl_fechaChanging(value);
                ReportPropertyChanging("sl_fecha");
                _sl_fecha = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sl_fecha");
                Onsl_fechaChanged();
            }
        }
        private global::System.String _sl_fecha;
        partial void Onsl_fechaChanging(global::System.String value);
        partial void Onsl_fechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sl_recepcion
        {
            get
            {
                return _sl_recepcion;
            }
            set
            {
                Onsl_recepcionChanging(value);
                ReportPropertyChanging("sl_recepcion");
                _sl_recepcion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_recepcion");
                Onsl_recepcionChanged();
            }
        }
        private Nullable<global::System.Boolean> _sl_recepcion;
        partial void Onsl_recepcionChanging(Nullable<global::System.Boolean> value);
        partial void Onsl_recepcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sl_asignacion
        {
            get
            {
                return _sl_asignacion;
            }
            set
            {
                Onsl_asignacionChanging(value);
                ReportPropertyChanging("sl_asignacion");
                _sl_asignacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_asignacion");
                Onsl_asignacionChanged();
            }
        }
        private Nullable<global::System.Boolean> _sl_asignacion;
        partial void Onsl_asignacionChanging(Nullable<global::System.Boolean> value);
        partial void Onsl_asignacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sl_atencion
        {
            get
            {
                return _sl_atencion;
            }
            set
            {
                Onsl_atencionChanging(value);
                ReportPropertyChanging("sl_atencion");
                _sl_atencion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_atencion");
                Onsl_atencionChanged();
            }
        }
        private Nullable<global::System.Boolean> _sl_atencion;
        partial void Onsl_atencionChanging(Nullable<global::System.Boolean> value);
        partial void Onsl_atencionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sl_aceptacion
        {
            get
            {
                return _sl_aceptacion;
            }
            set
            {
                Onsl_aceptacionChanging(value);
                ReportPropertyChanging("sl_aceptacion");
                _sl_aceptacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_aceptacion");
                Onsl_aceptacionChanged();
            }
        }
        private Nullable<global::System.Boolean> _sl_aceptacion;
        partial void Onsl_aceptacionChanging(Nullable<global::System.Boolean> value);
        partial void Onsl_aceptacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sl_eliminado
        {
            get
            {
                return _sl_eliminado;
            }
            set
            {
                Onsl_eliminadoChanging(value);
                ReportPropertyChanging("sl_eliminado");
                _sl_eliminado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sl_eliminado");
                Onsl_eliminadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _sl_eliminado;
        partial void Onsl_eliminadoChanging(Nullable<global::System.Boolean> value);
        partial void Onsl_eliminadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_DetalleSolicitud_Solicitud", "DetalleSolicitud")]
        public EntityCollection<DetalleSolicitud> DetalleSolicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleSolicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Solicitud", "DetalleSolicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleSolicitud>("CSCInventariosDBModel.FK_DetalleSolicitud_Solicitud", "DetalleSolicitud", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Solicitud_Estacion", "Estacion")]
        public Estacion Estacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacion>("CSCInventariosDBModel.FK_Solicitud_Estacion", "Estacion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacion>("CSCInventariosDBModel.FK_Solicitud_Estacion", "Estacion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estacion> EstacionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacion>("CSCInventariosDBModel.FK_Solicitud_Estacion", "Estacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estacion>("CSCInventariosDBModel.FK_Solicitud_Estacion", "Estacion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Inventario_Solicitud", "Inventario")]
        public EntityCollection<Inventario> Inventario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inventario>("CSCInventariosDBModel.FK_Inventario_Solicitud", "Inventario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inventario>("CSCInventariosDBModel.FK_Inventario_Solicitud", "Inventario", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Solicitud_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CSCInventariosDBModel.FK_Solicitud_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CSCInventariosDBModel.FK_Solicitud_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CSCInventariosDBModel.FK_Solicitud_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("CSCInventariosDBModel.FK_Solicitud_Usuario", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CSCInventariosDBModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="usuario_id">Valor inicial de la propiedad usuario_id.</param>
        public static Usuario CreateUsuario(global::System.Int32 usuario_id)
        {
            Usuario usuario = new Usuario();
            usuario.usuario_id = usuario_id;
            return usuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usuario_id
        {
            get
            {
                return _usuario_id;
            }
            set
            {
                if (_usuario_id != value)
                {
                    Onusuario_idChanging(value);
                    ReportPropertyChanging("usuario_id");
                    _usuario_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usuario_id");
                    Onusuario_idChanged();
                }
            }
        }
        private global::System.Int32 _usuario_id;
        partial void Onusuario_idChanging(global::System.Int32 value);
        partial void Onusuario_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario_nombre
        {
            get
            {
                return _usuario_nombre;
            }
            set
            {
                Onusuario_nombreChanging(value);
                ReportPropertyChanging("usuario_nombre");
                _usuario_nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario_nombre");
                Onusuario_nombreChanged();
            }
        }
        private global::System.String _usuario_nombre;
        partial void Onusuario_nombreChanging(global::System.String value);
        partial void Onusuario_nombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario_apellido
        {
            get
            {
                return _usuario_apellido;
            }
            set
            {
                Onusuario_apellidoChanging(value);
                ReportPropertyChanging("usuario_apellido");
                _usuario_apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario_apellido");
                Onusuario_apellidoChanged();
            }
        }
        private global::System.String _usuario_apellido;
        partial void Onusuario_apellidoChanging(global::System.String value);
        partial void Onusuario_apellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario_telefono
        {
            get
            {
                return _usuario_telefono;
            }
            set
            {
                Onusuario_telefonoChanging(value);
                ReportPropertyChanging("usuario_telefono");
                _usuario_telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario_telefono");
                Onusuario_telefonoChanged();
            }
        }
        private global::System.String _usuario_telefono;
        partial void Onusuario_telefonoChanging(global::System.String value);
        partial void Onusuario_telefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario_usuario
        {
            get
            {
                return _usuario_usuario;
            }
            set
            {
                Onusuario_usuarioChanging(value);
                ReportPropertyChanging("usuario_usuario");
                _usuario_usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario_usuario");
                Onusuario_usuarioChanged();
            }
        }
        private global::System.String _usuario_usuario;
        partial void Onusuario_usuarioChanging(global::System.String value);
        partial void Onusuario_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario_clave
        {
            get
            {
                return _usuario_clave;
            }
            set
            {
                Onusuario_claveChanging(value);
                ReportPropertyChanging("usuario_clave");
                _usuario_clave = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario_clave");
                Onusuario_claveChanged();
            }
        }
        private global::System.String _usuario_clave;
        partial void Onusuario_claveChanging(global::System.String value);
        partial void Onusuario_claveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> usuario_eliminado
        {
            get
            {
                return _usuario_eliminado;
            }
            set
            {
                Onusuario_eliminadoChanging(value);
                ReportPropertyChanging("usuario_eliminado");
                _usuario_eliminado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usuario_eliminado");
                Onusuario_eliminadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _usuario_eliminado;
        partial void Onusuario_eliminadoChanging(Nullable<global::System.Boolean> value);
        partial void Onusuario_eliminadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Requerimiento_Usuario", "Requerimiento")]
        public EntityCollection<Requerimiento> Requerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requerimiento>("CSCInventariosDBModel.FK_Requerimiento_Usuario", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requerimiento>("CSCInventariosDBModel.FK_Requerimiento_Usuario", "Requerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CSCInventariosDBModel", "FK_Solicitud_Usuario", "Solicitud")]
        public EntityCollection<Solicitud> Solicitud
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Solicitud>("CSCInventariosDBModel.FK_Solicitud_Usuario", "Solicitud");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Solicitud>("CSCInventariosDBModel.FK_Solicitud_Usuario", "Solicitud", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
